# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  api:
    build:
      context: .
    command:
      - "--api"
    environment:
      DB_PASSWD: secret
      DB_ADDR: db
      DB_PORT: 5432
    ports:
      - "5001:5001"

  rabbitmq:
    image: rabbitmq:3
    ports:
      - "5672:5672"

  db_manager:
    build:
      context: .
    command:
      - "--consumer"
    environment:
      DB_PASSWD: secret
      DB_ADDR: db
      DB_PORT: 5432
      RABBITMQ_PASSWD: guest
      RABBITMQ_USER: guest
      RABBITMQ_ADDR: rabbitmq
      RABBITMQ_PORT: 5672
