# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  api:
    build:
      context: .
    environment:
      PASSWD: secret
      DB_ADDR: db
      DB_PORT: 5432
    ports:
      - "5001:5001"
