version: '3.1'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  api:
    build:
      context: .
    command:
      - "--api"
    environment:
      DB_ADDR: postgres
    ports:
      - "5001:5001"

  rabbitmq:
    image: rabbitmq:3
    ports:
      - "5672:5672"

  db_manager:
    build:
      context: .
    command:
      - "--consumer"
    environment:
      DB_ADDR: postgres
      RABBITMQ_ADDR: rabbitmq
